name: Feature Branch

on:
  push:
    branches:
      - 'fix/*'
      - 'tools/*'
      - 'feature/*'
      - '!master'
      - '!release*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Gradle Cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Gradle Wrapper Cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-wrapper-

    - name: Set Up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Unit tests
      run: bash ./gradlew test --stacktrace

    - name: Upload Test HTML Result
      if: failure() || success()
      uses: actions/upload-artifact@v1
      with:
        name: test-result
        path: app/build/reports/tests/testDebugUnitTest/
